I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/combat4.rpy", line 141, in script
    image smol_ame = Movie(play = image/smolame.webm)
  File "game/combat4.rpy", line 141, in <module>
    image smol_ame = Movie(play = image/smolame.webm)
NameError: name 'image' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/combat4.rpy", line 141, in script
    image smol_ame = Movie(play = image/smolame.webm)
  File "C:\renpy-8.2.1-sdk\renpy\ast.py", line 922, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/combat4.rpy", line 141, in <module>
    image smol_ame = Movie(play = image/smolame.webm)
NameError: name 'image' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.1.24030407
The Chosen One 1.3
Tue Aug 13 09:40:11 2024
