I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scene3.rpy", line 86, in script
    show monster at middle with fade
  File "game/scene3.rpy", line 86, in <module>
    show monster at middle with fade
NameError: name 'middle' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scene3.rpy", line 86, in script
    show monster at middle with fade
  File "C:\renpy-8.2.1-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\renpy-8.2.1-sdk\renpy\ast.py", line 1072, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\renpy-8.2.1-sdk\renpy\ast.py", line 1072, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scene3.rpy", line 86, in <module>
    show monster at middle with fade
NameError: name 'middle' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.1.24030407
The Chosen One 1.3
Fri Aug  9 14:38:08 2024
